# Generated by Django 3.2 on 2021-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default='', max_length=255)),
                ('streaming_key', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
